### ISSUE TITLE
Error when trying to use Tutorial in R 

### ISSUE THREAD

**Issue by rhondataylor1** [kiadso/rTraining#2]
Hello,

I updated R to in order to get the training tab and tutorials.  I was able to update it and proceeded to install learnr.  It appeared to install successfully but when I click on Start Tutorial I receive the below error

![image](https://user-images.githubusercontent.com/67340886/85460764-99884d00-b571-11ea-9d73-4214ad52f090.png)

Not sure of what file it is looking for.

Thanks,
Rhonda 
rhonda.taylor@dca.ga.gov

**Comment by kiadso** [comment]
Try this in RStudio:
Go to Tools > Check for Package Updates and then click Select All and then click Install Updates.
Then try doing the Tutorial again and let me know what happens! 

Thanks for dropping a question here, Rhonda! I'll have to be sure I'm getting notified.

**Comment by rhondataylor1** [comment]
I receive the below message when clicking on "Check Package Updates"

![image](https://user-images.githubusercontent.com/67340886/85743606-2f3aee00-b6d2-11ea-9c38-5c0b5f95d5b7.png)

There's nothing in the box.  This is a fresh update, I'm using the below

![image](https://user-images.githubusercontent.com/67340886/85743874-6b6e4e80-b6d2-11ea-8e09-90794a7c772a.png)

**Comment by kiadso** [comment]
When you go to the Packages tab (bottom right quadrant in RStudio) and search on learnr, what version do you have? And what version of rstudioapi?

**Comment by rhondataylor1** [comment]
learnr 0.9.2.1
rstudioapi 0.10

**Comment by kiadso** [comment]
You might try:

`remove.packages("learnr")`

and then 

`install.packages("learnr")`

and then do the same thing with rstudioapi

**Comment by rhondataylor1** [comment]
Same error message from above regarding the version. 

What is and how do I check this getoption('"repos") to make sure it refers to a CRAN repository.

**Comment by kiadso** [comment]
I don't know, I've never used that. I have asked a friend though if she can help.

In the meantime, maybe try this: https://cran.r-project.org/bin/windows/contrib/4.0/learnr_0.10.1.zip

Download that zip file to somewhere you'll know how to find it.
Go to Tools, Install Packages, in the top droplist, select Package Archive File, then navigate to that zip file and try installing it that way.

**Comment by rhondataylor1** [comment]
Same error

![image](https://user-images.githubusercontent.com/67340886/85882079-a1800100-b7ac-11ea-9618-458f1830d028.png)

**Comment by kiadso** [comment]
We figured out user had installed R version 3.53 because when you google "install R", a link to that version shows up and it looks real enticing, but users need to click the one that just says "Windows". 

Updating R solved the problem.
